import { Task, Habit, ShoppingItem, UserProfile, ScheduleBlock, DailyQuest, CustomReward } from '../types';

export const getTodayDateString = (offsetDays = 0): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const DEFAULT_ADULT_PROFILE: UserProfile = {
  name: 'Alex Rivera',
  persona: 'adult',
  avatarSeed: 'alex',
  isPro: false,
  streakDays: 6,
  totalTasksCompleted: 42,
  referralCode: 'ALEX-LIFE-77',
  friendsReferred: 2,
  aiCreditsLeft: 10,
  xp: 340,
  level: 3,
  gems: 45,
  settings: {
    darkMode: false,
    soundEnabled: true,
    hapticFeedback: true,
    notificationsEnabled: true,
    largeFontMode: false,
    mobileFrameView: true,
    speechAudioEnabled: true,
    wakeTime: '07:00',
    bedTime: '23:00',
  },
};

export const INITIAL_QUESTS: DailyQuest[] = [
  { id: 'q-1', title: 'Complete 3 Priority Tasks', xpReward: 50, targetCount: 3, currentCount: 1, type: 'tasks', claimed: false },
  { id: 'q-2', title: 'Check off 2 Daily Habits', xpReward: 40, targetCount: 2, currentCount: 2, type: 'habits', claimed: true },
  { id: 'q-3', title: 'Complete 1 Pomodoro Focus Block', xpReward: 60, targetCount: 1, currentCount: 0, type: 'focus', claimed: false },
  { id: 'q-4', title: 'Review or Add to Shopping List', xpReward: 30, targetCount: 1, currentCount: 1, type: 'shop', claimed: false },
];

export const INITIAL_REWARDS: CustomReward[] = [
  { id: 'rew-1', title: '30-Minute Guilt-Free Break', costXp: 100, icon: '☕', description: 'Enjoy your favorite coffee, tea or walk.', claimedTimes: 2 },
  { id: 'rew-2', title: 'Movie Night & Popcorn', costXp: 250, icon: '🍿', description: 'Watch an episode or movie completely stress-free.', claimedTimes: 1 },
  { id: 'rew-3', title: 'Treat / Dessert of Choice', costXp: 180, icon: '🍦', description: 'Indulge in a sweet reward for great consistency.', claimedTimes: 0 },
  { id: 'rew-4', title: 'Weekend Special Activity', costXp: 400, icon: '🎉', description: 'Book a trip or exciting outing with friends/family.', claimedTimes: 0 },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't-1',
    title: 'Review Q4 Project Deliverables & Budget',
    description: 'Finalize presentation slides and align with the design lead.',
    category: 'Work',
    priority: 'urgent',
    completed: false,
    dueDate: getTodayDateString(0),
    dueTime: '11:00',
    estimatedMinutes: 45,
    favorite: true,
    reminderSet: true,
    createdAt: new Date().toISOString(),
    subtasks: [
      { id: 'sub-1', title: 'Check budget spreadsheet formula', completed: true },
      { id: 'sub-2', title: 'Export slide deck PDF', completed: false },
      { id: 'sub-3', title: 'Email team invite', completed: false },
    ],
  },
  {
    id: 't-2',
    title: 'Hydrate & 30-min Outdoor Walk',
    description: 'Get some midday sunlight and reset screen fatigue.',
    category: 'Health',
    priority: 'medium',
    completed: true,
    dueDate: getTodayDateString(0),
    dueTime: '13:00',
    estimatedMinutes: 30,
    favorite: false,
    reminderSet: false,
    createdAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
    subtasks: [],
  },
  {
    id: 't-3',
    title: 'Pick up dry cleaning & pharmacy refill',
    description: 'Before the store closes at 6:30 PM.',
    category: 'Personal',
    priority: 'high',
    completed: false,
    dueDate: getTodayDateString(0),
    dueTime: '17:30',
    estimatedMinutes: 35,
    favorite: true,
    reminderSet: true,
    createdAt: new Date().toISOString(),
    subtasks: [
      { id: 'sub-4', title: 'Bring claim ticket #419', completed: false },
      { id: 'sub-5', title: 'Check prescription refilled online', completed: true },
    ],
  },
  {
    id: 't-4',
    title: 'Organize study notes & chapter reading',
    description: 'Read Chapter 4 and highlight key concepts.',
    category: 'School',
    priority: 'medium',
    completed: false,
    dueDate: getTodayDateString(1),
    dueTime: '19:00',
    estimatedMinutes: 50,
    favorite: false,
    createdAt: new Date().toISOString(),
    subtasks: [
      { id: 'sub-6', title: 'Summary bullet points', completed: false },
      { id: 'sub-7', title: 'Flashcards on quizlet', completed: false },
    ],
  },
  {
    id: 't-5',
    title: 'Water house plants & kitchen basil',
    description: 'Mist ferns and fertilize monstera.',
    category: 'Home',
    priority: 'low',
    completed: true,
    dueDate: getTodayDateString(-1),
    dueTime: '08:30',
    estimatedMinutes: 10,
    createdAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
    subtasks: [],
  },
];

export const INITIAL_HABITS: Habit[] = [
  {
    id: 'h-1',
    title: 'Morning Sunlight & Glass of Water',
    category: 'Health',
    icon: 'Sun',
    frequency: 'daily',
    targetDaysPerWeek: 7,
    streak: 6,
    bestStreak: 18,
    completedDates: [
      getTodayDateString(-5),
      getTodayDateString(-4),
      getTodayDateString(-3),
      getTodayDateString(-2),
      getTodayDateString(-1),
      getTodayDateString(0),
    ],
    timeOfDay: 'morning',
    favorite: true,
    color: '#F59E0B',
    reminderTime: '07:15',
  },
  {
    id: 'h-2',
    title: 'Read 20 Pages of a Book',
    category: 'Personal',
    icon: 'BookOpen',
    frequency: 'daily',
    targetDaysPerWeek: 6,
    streak: 4,
    bestStreak: 12,
    completedDates: [
      getTodayDateString(-4),
      getTodayDateString(-3),
      getTodayDateString(-2),
      getTodayDateString(-1),
    ],
    timeOfDay: 'evening',
    favorite: true,
    color: '#8B5CF6',
    reminderTime: '21:30',
  },
  {
    id: 'h-3',
    title: '15-Minute Home Reset / Tidy',
    category: 'Home',
    icon: 'Sparkles',
    frequency: 'daily',
    targetDaysPerWeek: 5,
    streak: 3,
    bestStreak: 10,
    completedDates: [
      getTodayDateString(-3),
      getTodayDateString(-2),
      getTodayDateString(-1),
    ],
    timeOfDay: 'evening',
    favorite: false,
    color: '#10B981',
  },
  {
    id: 'h-4',
    title: 'Daily Budget Check & Receipt Log',
    category: 'Finance',
    icon: 'Wallet',
    frequency: 'weekdays',
    targetDaysPerWeek: 5,
    streak: 8,
    bestStreak: 14,
    completedDates: [
      getTodayDateString(-5),
      getTodayDateString(-4),
      getTodayDateString(-3),
      getTodayDateString(-2),
      getTodayDateString(-1),
      getTodayDateString(0),
    ],
    timeOfDay: 'afternoon',
    favorite: false,
    color: '#06B6D4',
  },
];

export const INITIAL_SHOPPING: ShoppingItem[] = [
  { id: 's-1', name: 'Organic Honeycrisp Apples', category: 'Produce', quantity: '5 pcs', estimatedPrice: 4.5, completed: false, favorite: true, addedAt: new Date().toISOString() },
  { id: 's-2', name: 'Oat Milk Barista Blend', category: 'Dairy & Eggs', quantity: '2 cartons', estimatedPrice: 7.99, completed: true, favorite: true, addedAt: new Date().toISOString() },
  { id: 's-3', name: 'Sourdough Artisan Bread', category: 'Bakery', quantity: '1 loaf', estimatedPrice: 4.25, completed: false, favorite: false, addedAt: new Date().toISOString() },
  { id: 's-4', name: 'Greek Yogurt (Plain 0%)', category: 'Dairy & Eggs', quantity: '32 oz', estimatedPrice: 5.49, completed: false, favorite: false, addedAt: new Date().toISOString() },
  { id: 's-5', name: 'Extra Virgin Olive Oil', category: 'Pantry', quantity: '1 bottle (750ml)', estimatedPrice: 11.99, completed: false, favorite: false, addedAt: new Date().toISOString() },
  { id: 's-6', name: 'Eco-Friendly Dish Sponge', category: 'Household', quantity: '3-pack', estimatedPrice: 3.5, completed: true, favorite: false, addedAt: new Date().toISOString() },
];

export const INITIAL_SCHEDULE: ScheduleBlock[] = [
  { id: 'sc-1', time: '07:30 - 08:00', title: 'Morning Glass of Water & Light Stretch', type: 'habit', tip: 'Hydrate before coffee for steady energy' },
  { id: 'sc-2', time: '08:30 - 09:15', title: 'Quick Emails & Daily Priority Triage', type: 'task', tip: 'Pick top 3 outcomes for today' },
  { id: 'sc-3', time: '09:30 - 11:30', title: 'Deep Focus: Q4 Project Deliverables', type: 'task', tip: 'Put phone on do not disturb' },
  { id: 'sc-4', time: '12:00 - 13:00', title: 'Healthy Lunch & 20m Walk Outside', type: 'break', tip: 'Rest your eyes from screens' },
  { id: 'sc-5', time: '14:00 - 16:00', title: 'Team Collaboration & Errands', type: 'personal', tip: 'Group external tasks together' },
  { id: 'sc-6', time: '21:00 - 21:45', title: 'Evening Reading & Wind Down', type: 'habit', tip: 'Dim lighting for restorative sleep' },
];

export const PERSONA_PRESETS: Record<string, { name: string; avatar: string; quote: string; tasks: Task[]; habits: Habit[] }> = {
  kid: {
    name: 'Leo (Kid Explorer)',
    avatar: 'leo',
    quote: 'Small steps every day make big superpowers! ⭐',
    tasks: [
      {
        id: 'tk-1',
        title: 'Pack Backpack for School',
        description: 'Put homework binder, pencil case, and water bottle inside.',
        category: 'School',
        priority: 'high',
        completed: false,
        dueDate: getTodayDateString(0),
        dueTime: '08:00',
        estimatedMinutes: 10,
        subtasks: [
          { id: 'sb-k1', title: 'Math worksheet', completed: true },
          { id: 'sb-k2', title: 'Library book', completed: false },
        ],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'tk-2',
        title: 'Feed Rover the Puppy',
        description: 'Fill water bowl and 1 scoop of kibble.',
        category: 'Home',
        priority: 'urgent',
        completed: true,
        dueDate: getTodayDateString(0),
        dueTime: '07:30',
        estimatedMinutes: 5,
        subtasks: [],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'tk-3',
        title: 'Practice 15 minutes of Piano',
        description: 'Play Song #3 two times slowly.',
        category: 'Personal',
        priority: 'medium',
        completed: false,
        dueDate: getTodayDateString(0),
        dueTime: '16:30',
        estimatedMinutes: 15,
        subtasks: [],
        createdAt: new Date().toISOString(),
      },
    ],
    habits: [
      {
        id: 'hk-1',
        title: 'Brush Teeth Morning & Night',
        category: 'Health',
        icon: 'Sparkles',
        frequency: 'daily',
        targetDaysPerWeek: 7,
        streak: 11,
        bestStreak: 20,
        completedDates: [getTodayDateString(-2), getTodayDateString(-1), getTodayDateString(0)],
        timeOfDay: 'morning',
        color: '#3B82F6',
      },
      {
        id: 'hk-2',
        title: 'Put Away Toys Before Bed',
        category: 'Home',
        icon: 'Home',
        frequency: 'daily',
        targetDaysPerWeek: 7,
        streak: 5,
        bestStreak: 12,
        completedDates: [getTodayDateString(-2), getTodayDateString(-1)],
        timeOfDay: 'evening',
        color: '#10B981',
      },
    ],
  },
  teen: {
    name: 'Maya (High School / Teen)',
    avatar: 'maya',
    quote: 'Stay focused on your goals, you got this! 🚀',
    tasks: [
      {
        id: 'tt-1',
        title: 'Chemistry Lab Report Submission',
        description: 'Upload PDF to classroom portal before midnight.',
        category: 'School',
        priority: 'urgent',
        completed: false,
        dueDate: getTodayDateString(0),
        dueTime: '23:59',
        estimatedMinutes: 45,
        subtasks: [
          { id: 'st-t1', title: 'Format graphs in Google Sheets', completed: true },
          { id: 'st-t2', title: 'Write error analysis paragraph', completed: false },
        ],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'tt-2',
        title: 'Soccer Practice & Hydration',
        description: 'Bring cleats and shin guards.',
        category: 'Health',
        priority: 'high',
        completed: true,
        dueDate: getTodayDateString(0),
        dueTime: '16:00',
        estimatedMinutes: 90,
        subtasks: [],
        createdAt: new Date().toISOString(),
      },
    ],
    habits: [
      {
        id: 'ht-1',
        title: '30-min Pomodoro Study Block',
        category: 'School',
        icon: 'Flame',
        frequency: 'weekdays',
        targetDaysPerWeek: 5,
        streak: 7,
        bestStreak: 14,
        completedDates: [getTodayDateString(-3), getTodayDateString(-2), getTodayDateString(-1), getTodayDateString(0)],
        timeOfDay: 'afternoon',
        color: '#F43F5E',
      },
      {
        id: 'ht-2',
        title: 'No Phone 30m Before Bed',
        category: 'Health',
        icon: 'Moon',
        frequency: 'daily',
        targetDaysPerWeek: 7,
        streak: 4,
        bestStreak: 9,
        completedDates: [getTodayDateString(-2), getTodayDateString(-1)],
        timeOfDay: 'evening',
        color: '#8B5CF6',
      },
    ],
  },
  adult: {
    name: 'Alex Rivera (Adult)',
    avatar: 'alex',
    quote: 'Clarity, calm execution, and steady progress. ✨',
    tasks: INITIAL_TASKS,
    habits: INITIAL_HABITS,
  },
};
